name: Tests
run-name: ${{ github.actor }} started the tests
on:
  pull_request:
  workflow_run:
    workflows:
      - Project Validation
    types:
      - completed
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install poetry
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: poetry install --with=dev
      - name: Execute tests with coverage
        run: poetry run pytest --cov --cov-report=xml --cov-report=term .
      - name: Report Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v3
#      - name: Run mypy validation
#        run: poetry run mypy .
